const data = [
  {
    id: 1,
    name: "Harsh Phawade",
    img: "team-24/harsh.jpg",
    pos: "Team Leader",
    linkedin: "https://www.linkedin.com/in/harsh-phawade-a94bb6250/",
  },
  {
    id: 2,
    name: "Swaraj Dangare",
    img: "team-24/swaraj.JPG",
    pos: "Team Manager",
    linkedin: "https://www.linkedin.com/in/swaraj-dangare-952a21214",
  },
  {
    id: 3,
    name: "Saatwik Vasishtha",
    img: "team-24/saatwik.JPG",
    pos: "Technical Head",
    linkedin: "https://www.linkedin.com/in/saatwik-vasishtha-974a82148/",
  },
  {
    id: 4,
    name: "Mallika Shinkre",
    img: "team-24/mallika.jpeg",
    pos: "Head of Operations",
    linkedin: "https://www.linkedin.com/in/mallika-shinkre-1ab030261",
  },
  {
    id: 5,
    name: "Aansh Basu",
    img: "team-24/aansh.jpg",
    pos: "Artificial Intelligence and Automation Head",
    linkedin: "https://www.linkedin.com/in/aansh-basu-628310251",
  },
  {
    id: 6,
    name: "Tarush Sonawala",
    img: "team-24/tarush.jpg",
    pos: "Electronics and Control Systems Head",
    linkedin: "https://www.linkedin.com/in/tarush-sonawala-43bb03217",
  },
  {
    id: 7,
    name: "Bharath Udupa",
    img: "team-24/bharath.jpg",
    pos: "Mechanical Design and Manufacturing Head",
    linkedin: "https://www.linkedin.com/in/bharath-u-7165281b2/",
  },
  {
    id: 8,
    name: "Rashi Goel",
    img: "team-24/rashi.jpg",
    pos: "Life Science Head",
    linkedin: "https://www.linkedin.com/in/rashi-goel-5a385a251?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BNS2OpZpBSwONbswI4FceIQ%3D%3D",
  },
  {
    id: 9,
    name: "Aditya Kasliwal",
    img: "team-24/aditya.jpg",
    pos: "Research Head",
    linkedin: "https://www.linkedin.com/in/aditya-kasliwal-982525227",
  },
  {
    id: 10,
    name: "Aarushi Anuj Dharna",
    img: "team-23/aarushi.webp",
    pos: "Mechanical Senior",
    linkedin: "https://www.linkedin.com/in/aarushi-dharna-84b1021b8",
  },
  {
    id: 11,
    name: "Arjunshankar S Menon",
    img: "team-23/arjun.webp",
    pos: "Mechanical Senior",
    linkedin: "https://www.linkedin.com/in/arjunshankar-menon-65951a221",
  },
  {
    id: 12,
    name: "Sanya Gupta",
    img: "team-23/sanya.webp",
    pos: "Mechanical Senior",
    linkedin: "https://www.linkedin.com/in/sanya-gupta-790750251",
  },
  {
    id: 13,
    name: "Shantanu Baranwal",
    img: "team-23/shantanu.webp",
    pos: "Mechanical Senior",
    linkedin: "https://www.linkedin.com/in/shantanu-baranwal-a98a74250",
  },
  {
    id: 14,
    name: "Shivansh Bansal",
    img: "team-23/shivansh.webp",
    pos: "Mechanical Senior",
    linkedin: "https://www.linkedin.com/in/shivansh-bansal-04bbb2250",
  },
  {
    id: 15,
    name: "Vipul Dinesh",
    img: "team-24/junior/mechanical/vipul.webp",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/vipul-dinesh",
  },
  {
    id: 16,
    name: "Suryank Joshi",
    img: "team-24/junior/mechanical/suryank.webp",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/suryank-joshi/",
  },
  {
    id: 17,
    name: "Het Ambaliya",
    img: "team-24/junior/mechanical/het.webp",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/het-ambaliya-5757b4253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 18,
    name: "Sanchit Dhingra",
    img: "team-24/junior/mechanical/sanchit.webp",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/sanchitdhingra",
  },
  {
    id: 19,
    name: "Vrishin Ashlyn Lakra",
    img: "team-24/junior/mechanical/vrishin.webp",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/vrishin-ashlyn-lakra-46858a257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 20,
    name: "Gagan Kiran Menderkar",
    img: "team-25/gagan.jpeg",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/gagan-menderkar-b3a243255?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 21,
    name: "Vivek Kolekar",
    img: "team-24/junior/mechanical/vivek.webp",
    pos: "Mechanical",
    linkedin: "https://www.linkedin.com/in/vivek-kolekar-19689721b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 22,
    name: "Harsh Nandwani",
    img: "team-23/harshn.webp",
    pos: "AI & Automation Senior",
    linkedin: "https://www.linkedin.com/in/harsh-nandwani-57a238212",
  },
  {
    id: 23,
    name: "Mustafa Haji",
    img: "team-25/mustafa.jpeg",
    pos: "AI & Automation",
    linkedin: "https://www.linkedin.com/in/mustafa-haji-3057611b0/",
  },
  {
    id: 24,
    name: "Ankur Monga",
    img: "team-25/ankur.jpg",
    pos: "AI & Automation",
    linkedin: "https://www.linkedin.com/in/ankur-monga-848020205",
  },
  {
    id: 25,
    name: "Prateek Manoj Mhatre ",
    img: "team-24/junior/ai/prateek.webp",
    pos: "AI & Automation",
    linkedin: "https://www.linkedin.com/in/prateek-mhatre-54a076235?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 26,
    name: "Nikhilesh Shashikumar",
    img: "team-24/junior/ai/nikhilesh.webp",
    pos: "AI & Automation",
    linkedin: "https://www.linkedin.com/in/nikhilesh-shashikumar-079a58259/",
  },
  {
    id: 27,
    name: "G.Siddharth Reddy",
    img: "team-24/junior/ai/siddharth.webp",
    pos: "AI & Automation",
    linkedin: "https://in.linkedin.com/in/siddharth-reddy-gangireddy-421a5624b",
  },
  {
    id: 28,
    name: "Vyshnav Davanagere Nagaraj",
    img: "team-24/junior/ai/vyshnav.webp",
    pos: "AI & Automation",
    linkedin: "https://www.linkedin.com/in/vyshnav-davanagere-789364250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    id: 29,
    name: "Hrishikesh M Rao",
    img: "team-23/hrishikesh.webp",
    pos: "Electronics & Control Systems Senior",
    linkedin: "https://www.linkedin.com/in/hrishikesh-m-rao-443a1b22a",
  },
  {
    id: 30,
    name: "Raj Nandini",
    img: "team-23/nandini.webp",
    pos: "Electronics & Control Systems Senior",
    linkedin: "https://www.linkedin.com/in/raj-nandini-6b85b6214",
  },
  {
    id: 31,
    name: "Aryavarta Singh",
    img: "team-24/junior/ecs/aryavarta.webp",
    pos: "Electronics & Control Systems",
    linkedin: "https://www.linkedin.com/in/aryavarta-singh-832689195?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 32,
    name: "Piyush Daigavhane",
    img: "team-24/junior/ecs/piyush.webp",
    pos: "Electronics & Control Systems",
    linkedin: "https://www.linkedin.com/in/piyush-daigavhane-9188b3228",
  },
  {
    id: 33,
    name: 'Saransh Andharmule',
    img: 'team-23/saransh.webp',
    pos: "Life Science Senior",
    linkedin: "https://www.linkedin.com/in/saransh-andharmule-a00952226",
  },
  {
    id: 34,
    name: 'Pritha Jaipal',
    img: 'team-23/pritha.webp',
    pos: "Life Science Senior",
    linkedin: "https://www.linkedin.com/in/pritha-jaipal-058b85187/",
  },
  {
    id: 35,
    name: 'Arooja Tyagi',
    img: 'team-24/junior/ls/arooja.webp',
    pos: "Life Science",
    linkedin: "https://www.linkedin.com/in/arooja-tyagi-10639b248/",
  },
  {
    id: 37,
    name: 'Sanvi Shetty',
    img: 'team-24/junior/ls/sanvi.webp',
    pos: "Life Science",
    linkedin: "https://www.linkedin.com/in/sanvi-shetty-83b325289?trk=contact-info",
  },
  {
    id: 38,
    name: 'Mitwa Saraf',
    img: 'team-24/junior/ls/mitwa.webp',
    pos: "Life Science",
    linkedin: "https://www.linkedin.com/in/mitwa-saraf-36a397239/",
  },
  {
    id: 39,
    name: 'Diya Mehta',
    img: 'team-23/diya.webp',
    pos: 'Research Senior',
    linkedin: "https://www.linkedin.com/in/diya-mehta-5333b9238/",
  },
  {
    id: 40,
    name: 'Ritika Ravichandran',
    img: 'team-23/ritika.webp',
    pos: 'Research Senior',
    linkedin: "https://www.linkedin.com/mwlite/in/ritika-ravichandran-a565b9221",
  },
  {
    id: 41,
    name: 'Pallavi Kailas',
    img: 'team-24/junior/research/pallavi.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/pallavi-kailas-65b561245?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    id: 42,
    name: 'Laven Srivastava',
    img: 'team-24/junior/research/laven.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/laven-srivastava-b1371223b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 43,
    name: 'Sankarshanaa Sagaram',
    img: 'team-24/junior/research/sanky.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/diya-mehta-5333b9238/",
  },
  {
    id: 44,
    name: 'Krish Didwania',
    img: 'team-24/junior/research/krish.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/krish-didwania-1a2395298?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
  {
    id: 45,
    name: 'Swetha Vemulapalli',
    img: 'team-24/junior/research/swetha.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/swetha-vemulapalli-b8374524b/",
  },
  {
    id: 46,
    name: 'Ishaan Gakhar',
    img: 'team-24/junior/research/ishaan.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/ishaan-gakhar-9248b8253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    id: 47,
    name: 'Nirbhay singhal',
    img: 'team-24/junior/research/nirbhay.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/nirbhaysinghal09/",
  },
  {
    id: 48,
    name: 'Ansh Sankrityayan',
    img: 'team-24/junior/research/ansh.webp',
    pos: 'Research',
    linkedin: "https://www.linkedin.com/in/anshsankrityayan/",
  }
];

export default data;