const data = [
    {
        id: 1,
        name: "Jyotishka Duttagupta",
        img: "team-22/jyotishka.webp",
        pos: "Team Leader",
        linkedin: "https://www.linkedin.com/in/jyotishka-duttagupta-20581a1a9",
      },
      {
        id: 2,
        name: "Piyush Raj",
        img: "team-22/piyush.webp",
        pos: "Team Manager",
        linkedin: "https://www.linkedin.com/in/piyush-raj-046507188/",
      },
      {
        id: 3,
        name: "Atirav Seth",
        img: "team-22/atirav.webp",
        pos: "Technical Head",
        linkedin: "https://www.linkedin.com/in/atirav-seth-0434801a9",
      },
      {
        id: 4,
        name: "Keshav Kapur",
        img: "team-22/keshav.jpeg",
        pos: "Artificial Intelligence & Automation Head",
        linkedin: "https://www.linkedin.com/in/keshav-kapur-80572b17a",
      },
      {
        id: 5,
        name: "Apoorv Thapliyal",
        img: "team-22/Apoorv.webp",
        pos: "Electronics & Control Systems Head",
        linkedin: "https://www.linkedin.com/in/apoorv-thapliyal-280a151a6",
      },
      {
        id: 7,
        name: "Abhishek Sankar",
        img: "team-22/Abhishek.webp",
        pos: "Mechanical Design & Manufacturing Head",
        linkedin:
          "https://www.linkedin.com/in/abhishek-sankar-6664071b2?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B7S1447W2QFCQ9v7Ng5k3Nw%3D%3D",
      },
      {
        id: 6,
        name: "Kumud Lakara",
        img: "team-22/Kumud.webp",
        pos: "Research Head",
        linkedin: "http://linkedin.com/in/kumud-lakara-8705641a5",
      },
      {
        id: 8,
        img: "team-22/aayush.jpeg",
        pos: "Web Development & Public Relations Senior",
        name: "Aayush R Shah",
        linkedin: "https://www.linkedin.com/in/aayush-shah-35591319a",
      },
    
      {
        id: 9,
        img: "team-22/Kirti Kedia.webp",
        pos: "Web Development & Public Relations",
        name: "Kirti Kedia",
        linkedin: "https://www.linkedin.com/in/kirti-kedia-440714204",
      },
      {
        id: 10,
        name: "Jordan Kuruvilla",
        pos: "Mechanical Senior",
        img: "team-22/jordan.jpeg",
        linkedin: "https://www.linkedin.com/mwlite/in/jordankuruvilla",
      },
      {
        id: 12,
        name: "Shashwat Sharma",
        pos: "Mechanical Senior",
        img: "team-22/shaswat.webp",
        linkedin: "https://www.linkedin.com/in/shashwat-sharma-0729121a9/",
      },
      {
        id: 13,
        name: "Akhilesh Jhawar",
        img: "team-22/Akhilesh.jpeg",
        pos: "Mechanical",
        linkedin: "http://linkedin.com/in/akhilesh-jhawar-77097a140",
      },
      {
        id: 14,
        name: "Amritanshu Jain",
        img: "team-22/AmritanshuJain.webp",
        pos: "Mechanical",
        linkedin: "http://linkedin.com/in/amritanshujain",
      },
      {
        id: 15,
        name: "Ankit Aggarwal",
        img: "team-22/AnkitAggarwal.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/ankit-aggarwal-04b5211b4",
      },
      {
        id: 16,
        name: "Ishayu Chakravorty",
        img: "team-22/Ishayu.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/ishayu-chakravorty-699955216",
      },
      {
        id: 17,
        name: "Jeswanthi Tirupathi",
        img: "team-22/Jeswanthi.webp",
        pos: "Mechanical",
        linkedin: "http://www.linkedin.com/in/jeswanthi-tirupathi-541695216",
      },
      {
        id: 18,
        name: "Saurabh Chaughule",
        img: "team-22/Saurabh.png",
        pos: "Mechanical",
        linkedin: "http://www.linkedin.com/in/saurabh-chaughule-740627200",
      },
      {
        id: 19,
        name: "Yashas Rao P",
        img: "team-22/YashashRao.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/yashash-rao-151a90216/",
      },
      {
        id: 21,
        name: "Aditya Arun Iyer",
        img: "team-22/Aditya Arun Iyer.webp",
        pos: "AI & Automation",
        linkedin: "http://www.linkedin.com/in/adityaaruniyer",
      },
      {
        id: 22,
        name: "Dishita Midha",
        img: "team-22/Dishita Midha.webp",
        pos: "AI & Automation",
        linkedin: "https://www.linkedin.com/in/dishita-midha-960755214/",
      },
      {
        id: 23,
        name: "Saipranav Vojjala",
        img: "team-22/Saipranav Vojjala.webp",
        pos: "AI & Automation",
        linkedin: "http://www.linkedin.com/in/saipranav-vojjala-2770ab217",
      },
      {
        id: 24,
        name: "Vanisha Agarwal",
        img: "team-22/Vanisha.webp",
        pos: "AI & Automation",
        linkedin: "http://www.linkedin.com/in/vanisha-agarwal-29240a1b4",
      },
      {
        id: 25,
        name: "Vignesh S Iyer",
        img: "team-22/vignesh iyer.webp",
        pos: "AI & Automation",
        linkedin: "http://www.linkedin.com/in/vignesh-iyer-630b48217",
      },
      {
        id: 31,
        name: "Devansh Mehra",
        pos: "Electronics Senior",
        img: "team-22/Devansh.jpg",
        linkedin: "https://www.linkedin.com/in/devansh-mehra-877753189",
      },
      {
        id: 32,
        name: "Jugal Jesing",
        pos: "Electronics Senior",
        img: "team-22/Jugal.webp",
        linkedin: "https://www.linkedin.com/in/jugal-jesing-1256841a9",
      },
      {
        id: 33,
        name: "Sreevatsan Rangaprasad",
        pos: "Electronics Senior",
        img: "team-22/Sreevatsan.webp",
        linkedin: "https://www.linkedin.com/in/sreevatsan-rangaprasad-43a190179",
      },
      {
        id: 34,
        name: "Aditya Harlalka",
        img: "team-22/Aditya.webp",
        pos: "Electronics",
        linkedin: "https://www.linkedin.com/in/aditya-harlalka-aba804173/",
      },
      {
        id: 35,
        name: "Kanishk Kaushal",
        img: "team-22/Kanishk.jpeg",
        pos: "Electronics",
        linkedin: "https://www.linkedin.com/in/kanishk-kaushal-18a24520b",
      },
      {
        id: 37,
        name: "Meet Jain ",
        img: "team-22/Meet.webp",
        pos: "Electronics",
        linkedin: "http://www.linkedin.com/in/meet-jain-b3632820a",
      },
      {
        id: 38,
        name: "Priya Baphna",
        img: "team-22/Priya.webp",
        pos: "Electronics",
        linkedin: "https://www.linkedin.com/mwlite/in/priya-baphna-554b82217",
      },
      {
        id: 39,
        name: "Tarush Sharma",
        img: "team-22/Tarush.webp",
        pos: "Electronics",
        linkedin: "https://www.linkedin.com/in/tarush-sharma-6724a61a0/",
      },
      {
        id: 41,
        name: 'Himanshu Sandhu',
        pos: "Science",
        img: 'team-22/Himanshu.jpg',
        linkedin: "https://www.linkedin.com/in/himanshu-sandhu-035b52217/",
      },
      {
        id: 42,
        name: 'Jahnavi Sri Dhanya',
        pos: "Science",
        img: 'team-22/Jahnavi.webp',
        linkedin: "https://www.linkedin.com/in/jahnavi-sri-dhanya-83993a200/",
      },
      {
        id: 43,
        name: 'Pavan Kumar Thota',
        pos: "Science",
        img: 'team-22/Pavan.jpg',
        linkedin: "https://www.linkedin.com/in/pavan-kumar-thota-9676a61b5",
      },
      {
        id: 44,
        name: 'Varsha R',
        pos: "Science",
        img: 'team-22/Varsha.webp',
        linkedin: "https://www.linkedin.com/in/varsha-r-784891213/",
      },
      {
        id: 52,
        name: 'Harshil Bhatt',
        pos: "Research Senior",
        img: 'team-22/Harshil.jpg',
        linkedin: "https://linkedin.com/in/harshilbhatt2001",
      },
      {
        id: 55,
        name: 'Akshat Bhandari',
        pos: "Research",
        img: 'team-22/AkshatBhandari.webp',
        linkedin: "https://www.linkedin.com/in/akshat-bhandarixv/",
      },
      {
        id: 56,
        name: 'Ashish Sharma',
        pos: "Research",
        img: 'team-22/AshishSharma.webp',
        linkedin: "https://www.linkedin.com/in/ashish-sharma-89a6431ba/",
      },
      {
        id: 57,
        name: 'Pratinav Seth',
        pos: "Research",
        img: 'team-22/PratinavSeth.webp',
        linkedin: "https://www.linkedin.com/in/pratinav-seth",
      },
  ];
  
  export default data;
  