const data = [
    {
        id: 1,
        name: "Yashas Rao P",
        img: "team-23/yashash.webp",
        pos: "Team Leader",
        linkedin: "https://www.linkedin.com/in/yashash-rao-151a90216/",
      },
      {
        id: 2,
        name: "Akhilesh Jhawar",
        img: "team-23/akhilesh.webp",
        pos: "Team Manager",
        linkedin: "http://linkedin.com/in/akhilesh-jhawar-77097a140",
      },
      {
        id: 3,
        name: "Ankit Aggarwal",
        img: "team-23/AnkitAggarwal.webp",
        pos: "Technical Head",
        linkedin: "https://www.linkedin.com/in/ankit-aggarwal-04b5211b4",
      },
      {
        id: 4,
        name: "Aditya Arun Iyer",
        img: "team-23/adityaai.jpeg",
        pos: "Artificial Intelligence & Automation Head",
        linkedin: "http://www.linkedin.com/in/adityaaruniyer",
      },
      {
        id: 5,
        name: "Meet Jain",
        img: "team-23/meet.webp",
        pos: "Electronics & Control Systems Head",
        linkedin: "http://www.linkedin.com/in/meet-jain-b3632820a",
      },
      {
        id: 6,
        name: "Amritanshu Jain",
        img: "team-23/amritanshu.webp",
        pos: "Mechanical Design & Manufacturing Head",
        linkedin: "http://linkedin.com/in/amritanshujain",
      },
      {
        id: 7,
        name: 'Pavan Kumar Thota',
        pos: "Science",
        img: 'team-23/pavan.jpg',
        pos: "Life Science Head",
        linkedin: "https://www.linkedin.com/in/pavan-kumar-thota-9676a61b5",
      },
      {
        id: 8,
        name: "Ashish Sharma",
        img: "team-23/ashish.webp",
        pos: "Research Head",
        linkedin: "https://www.linkedin.com/in/ashish-sharma-89a6431ba/",
      },
      {
        id: 9,
        name: "Ishayu Chakravorty",
        img: "team-23/ishayu.webp",
        pos: "Mechanical Senior",
        linkedin: "https://www.linkedin.com/in/ishayu-chakravorty-699955216",
      },
      {
        id: 10,
        name: "Jeswanthi Tirupathi",
        img: "team-23/jeswanthi.webp",
        pos: "Mechanical Senior",
        linkedin: "http://www.linkedin.com/in/jeswanthi-tirupathi-541695216",
      },
      {
        id: 11,
        name: "Saurabh Chaughule",
        img: "team-23/saurabh.png",
        pos: "Mechanical Senior",
        linkedin: "http://www.linkedin.com/in/saurabh-chaughule-740627200",
      },
      {
        id: 12,
        name: "Aarushi Anuj Dharna",
        img: "team-23/aarushi.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/aarushi-dharna-84b1021b8",
      },
      {
        id: 13,
        name: "Arjunshankar S Menon",
        img: "team-23/arjun.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/arjunshankar-menon-65951a221",
      },
      {
        id: 14,
        name: "Sanya Gupta",
        img: "team-23/sanya.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/sanya-gupta-790750251",
      },
      {
        id: 15,
        name: "Shantanu Baranwal",
        img: "team-23/shantanu.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/shantanu-baranwal-a98a74250",
      },
      {
        id: 16,
        name: "Shivansh Bansal",
        img: "team-23/shivansh.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/shivansh-bansal-04bbb2250",
      },
      {
        id: 17,
        name: "Bharath Udupa",
        img: "team-23/bharath.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/bharath-u-7165281b2/",
      },
      {
        id: 18,
        name: "Harsh Phawade",
        img: "team-23/harshp.webp",
        pos: "Mechanical",
        linkedin: "https://www.linkedin.com/in/harsh-phawade-a94bb6250/",
      },
      {
        id: 19,
        name: "Dishita Midha",
        img: "team-23/dishita.webp",
        pos: "AI & Automation Senior",
        linkedin: "https://www.linkedin.com/in/dishita-midha-960755214/",
      },
      {
        id: 20,
        name: "Saipranav Vojjala",
        img: "team-23/saipranav.webp",
        pos: "AI & Automation Senior",
        linkedin: "http://www.linkedin.com/in/saipranav-vojjala-2770ab217",
      },
      {
        id: 21,
        name: "Vignesh S Iyer",
        img: "team-22/vignesh iyer.webp",
        pos: "AI & Automation Senior",
        linkedin: "http://www.linkedin.com/in/vignesh-iyer-630b48217",
      },
      {
        id: 22,
        name: "Aansh Basu",
        img: "team-23/aansh.webp",
        pos: "AI & Automation",
        linkedin: "https://www.linkedin.com/in/aansh-basu-628310251",
      },
      {
        id: 23,
        name: "Harsh Nandwani",
        img: "team-23/harshn.webp",
        pos: "AI & Automation",
        linkedin: "https://www.linkedin.com/in/harsh-nandwani-57a238212",
      },
      {
        id: 24,
        name: "Saatwik Vasishtha",
        img: "team-23/saatwik.webp",
        pos: "AI & Automation",
        linkedin: "https://www.linkedin.com/in/saatwik-vasishtha-974a82148/",
      },
      {
        id: 25,
        name: "Kanishk Kaushal",
        img: "team-23/kanishk.jpeg",
        pos: "Electronics & Control Systems Senior",
        linkedin: "https://www.linkedin.com/in/kanishk-kaushal-18a24520b",
      },
      {
        id: 26,
        name: "Hrishikesh M Rao",
        img: "team-23/hrishikesh.webp",
        pos: "Electronics & Control Systems",
        linkedin: "https://www.linkedin.com/in/hrishikesh-m-rao-443a1b22a",
      },
      {
        id: 27,
        name: "Raj Nandini",
        img: "team-23/nandini.webp",
        pos: "Electronics & Control Systems",
        linkedin: "https://www.linkedin.com/in/raj-nandini-6b85b6214",
      },
      {
        id: 28,
        name: "Swaraj Dangare",
        img: "team-23/swaraj.webp",
        pos: "Electronics & Control Systems",
        linkedin: "https://www.linkedin.com/in/swaraj-dangare-952a21214",
      },
      {
        id: 29,
        name: "Tarush Sonawala",
        img: "team-23/tarush.webp",
        pos: "Electronics & Control Systems",
        linkedin: "https://www.linkedin.com/in/tarush-sonawala-43bb03217",
      },
      {
        id: 30,
        name: "Uttiya Sangiri",
        img: "team-23/uttiya.webp",
        pos: "Electronics & Control Systems",
        linkedin: "https://www.linkedin.com/in/uttiya-sangiri/",
      },
      {
        id: 31,
        name: 'Varsha R',
        img: 'team-23/varsha.webp',
        pos: "Life Science Senior",
        linkedin: "https://www.linkedin.com/in/varsha-r-784891213/",
      },
      {
        id: 32,
        name: 'Mallika Shinkre',
        img: 'team-23/mallika.webp',
        pos: "Life Science",
        linkedin: "https://www.linkedin.com/in/mallika-shinkre-1ab030261",
      },
      {
        id: 33,
        name: 'Pritha Jaipal',
        img: 'team-23/pritha.webp',
        pos: "Life Science",
        linkedin: "https://www.linkedin.com/in/pritha-jaipal-058b85187/",
      },
      {
        id: 34,
        name: 'Rashi Goel',
        img: 'team-23/rashi.webp',
        pos: "Life Science",
        linkedin: "https://www.linkedin.com/in/rashi-goel-5a385a251?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BNS2OpZpBSwONbswI4FceIQ%3D%3D",
      },
      {
        id: 35,
        name: 'Saransh Andharmule',
        img: 'team-23/saransh.webp',
        pos: "Life Science",
        linkedin: "https://www.linkedin.com/in/saransh-andharmule-a00952226",
      },
      {
        id: 36,
        name: 'Akshat Bhandari',
        img: 'team-23/akshat.webp',
        pos: "Research Senior",
        linkedin: "https://www.linkedin.com/in/akshat-bhandarixv/",
      },
      {
        id: 37,
        name: 'Pratinav Seth',
        img: 'team-23/pratinav.webp',
        pos: "Research Senior",
        linkedin: "https://www.linkedin.com/in/pratinav-seth",
      },
      {
        id: 38,
        name: 'Adil K',
        img: 'team-23/adil.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/adil-k-ba37161a2",
      },
      {
        id: 39,
        name: 'Aditya Kasliwal',
        img: 'team-23/adityak.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/aditya-kasliwal-982525227",
      },
      {
        id: 40,
        name: 'Ananya Gupta',
        img: 'team-23/ananya.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/ananya-gupta-982414204",
      },
      {
        id: 41,
        name: 'Diya Mehta',
        img: 'team-23/diya.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/diya-mehta-5333b9238/",
      },
      {
        id: 42,
        name: 'Ritika Ravichandran',
        img: 'team-23/ritika.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/mwlite/in/ritika-ravichandran-a565b9221",
      },
      {
        id: 43,
        name: 'Sanchit Singhal',
        img: 'team-23/sanchit.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/sanchit-singhal-851239220",
      },
      {
        id: 44,
        name: 'Sriya Rallabandi',
        img: 'team-23/sriya.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/sriya-rallabandi-1a614020a",
      },
      {
        id: 45,
        name: 'Saurabh Kumar Mishra',
        img: 'team-23/saurabhm.webp',
        pos: "Research",
        linkedin: "https://www.linkedin.com/in/saurabh-mishra-5a0719218",
      }
      
  ];
  
  export default data;
  